export const MCP_CATEGORIES = [
    { id: 'filesystem', labelKey: 'claude.mcpCatFilesystem' },
    { id: 'devtools', labelKey: 'claude.mcpCatDevtools' },
    { id: 'database', labelKey: 'claude.mcpCatDatabase' },
    { id: 'web', labelKey: 'claude.mcpCatWeb' },
    { id: 'ai', labelKey: 'claude.mcpCatAi' },
    { id: 'cloud', labelKey: 'claude.mcpCatCloud' },
    { id: 'communication', labelKey: 'claude.mcpCatCommunication' },
    { id: 'utilities', labelKey: 'claude.mcpCatUtilities' },
];
export const MCP_CATEGORY_ICONS = {
    filesystem: '\uD83D\uDCC1',
    devtools: '\uD83D\uDEE0',
    database: '\uD83D\uDDC4',
    web: '\uD83C\uDF10',
    ai: '\uD83E\uDDE0',
    cloud: '\u2601\uFE0F',
    communication: '\uD83D\uDCAC',
    utilities: '\u2699\uFE0F',
};
export const MCP_CATALOG = [
    // === Filesystem ===
    {
        id: 'filesystem',
        name: 'Filesystem',
        description: 'Secure file operations with configurable access controls',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '/tmp'],
        category: 'filesystem',
        features: ['read_file', 'write_file', 'list_directory', 'move_file', 'search_files', 'get_file_info'],
        official: true,
    },
    {
        id: 'git',
        name: 'Git',
        description: 'Read, search, and manipulate Git repositories',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-git'],
        category: 'devtools',
        features: ['git_status', 'git_log', 'git_diff', 'git_commit', 'git_branch', 'git_checkout'],
        official: true,
    },
    {
        id: 'memory',
        name: 'Memory',
        description: 'Knowledge graph-based persistent memory system',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-memory'],
        category: 'ai',
        features: ['create_entities', 'create_relations', 'search_nodes', 'open_nodes', 'delete_entities'],
        official: true,
    },
    // === Web ===
    {
        id: 'fetch',
        name: 'Fetch',
        description: 'Web content fetching and conversion for efficient LLM usage',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-fetch'],
        category: 'web',
        features: ['fetch_url', 'fetch_html', 'fetch_markdown', 'fetch_json'],
        official: true,
    },
    {
        id: 'brave-search',
        name: 'Brave Search',
        description: 'Web and local search using Brave Search API',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-brave-search'],
        env: { BRAVE_API_KEY: '' },
        envPlaceholders: { BRAVE_API_KEY: 'your-brave-api-key' },
        category: 'web',
        features: ['brave_web_search', 'brave_local_search'],
        official: true,
    },
    {
        id: 'puppeteer',
        name: 'Puppeteer',
        description: 'Browser automation and web scraping',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-puppeteer'],
        category: 'web',
        features: ['navigate', 'screenshot', 'click', 'fill', 'evaluate', 'select'],
        official: true,
    },
    {
        id: 'playwright',
        name: 'Playwright',
        description: 'Browser automation with Playwright for testing and scraping',
        command: 'npx',
        args: ['-y', '@anthropic-ai/mcp-server-playwright'],
        category: 'web',
        features: ['navigate', 'screenshot', 'click', 'fill', 'select', 'evaluate'],
        official: false,
    },
    // === AI ===
    {
        id: 'sequential-thinking',
        name: 'Sequential Thinking',
        description: 'Dynamic and reflective problem-solving through thought sequences',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
        category: 'ai',
        features: ['create_thought', 'chain_thoughts', 'branch_thoughts', 'revise_thought'],
        official: true,
    },
    // === Database ===
    {
        id: 'postgres',
        name: 'PostgreSQL',
        description: 'Read-only access to PostgreSQL databases',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-postgres'],
        env: { POSTGRES_CONNECTION_STRING: '' },
        envPlaceholders: { POSTGRES_CONNECTION_STRING: 'postgresql://user:pass@localhost:5432/db' },
        category: 'database',
        features: ['query', 'list_tables', 'describe_table'],
        official: true,
    },
    {
        id: 'sqlite',
        name: 'SQLite',
        description: 'Database interaction and business intelligence for SQLite',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sqlite', '--db-path', '/path/to/db.sqlite'],
        category: 'database',
        features: ['read_query', 'write_query', 'create_table', 'list_tables', 'describe_table', 'append_insight'],
        official: true,
    },
    {
        id: 'redis',
        name: 'Redis',
        description: 'Interact with Redis key-value stores',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-redis'],
        env: { REDIS_URL: '' },
        envPlaceholders: { REDIS_URL: 'redis://localhost:6379' },
        category: 'database',
        features: ['get', 'set', 'delete', 'list_keys', 'info'],
        official: true,
    },
    // === DevTools ===
    {
        id: 'github',
        name: 'GitHub',
        description: 'Repository management, file operations, and GitHub API integration',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-github'],
        env: { GITHUB_PERSONAL_ACCESS_TOKEN: '' },
        envPlaceholders: { GITHUB_PERSONAL_ACCESS_TOKEN: 'ghp_your_token' },
        category: 'devtools',
        features: ['create_issue', 'list_issues', 'create_pull_request', 'search_repositories', 'get_file_contents', 'push_files'],
        official: true,
    },
    {
        id: 'gitlab',
        name: 'GitLab',
        description: 'GitLab API integration for project management',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-gitlab'],
        env: { GITLAB_PERSONAL_ACCESS_TOKEN: '', GITLAB_API_URL: '' },
        envPlaceholders: { GITLAB_PERSONAL_ACCESS_TOKEN: 'glpat-your_token', GITLAB_API_URL: 'https://gitlab.com/api/v4' },
        category: 'devtools',
        features: ['create_issue', 'list_projects', 'create_merge_request', 'get_file_contents'],
        official: true,
    },
    {
        id: 'sentry',
        name: 'Sentry',
        description: 'Retrieve and analyze issues from Sentry.io',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sentry'],
        env: { SENTRY_AUTH_TOKEN: '' },
        envPlaceholders: { SENTRY_AUTH_TOKEN: 'your-sentry-token' },
        category: 'devtools',
        features: ['list_issues', 'get_issue_details', 'list_projects', 'resolve_issue'],
        official: true,
    },
    // === Cloud ===
    {
        id: 'google-drive',
        name: 'Google Drive',
        description: 'File access and search capabilities for Google Drive',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-gdrive'],
        category: 'cloud',
        features: ['search_files', 'read_file', 'list_files'],
        official: true,
    },
    {
        id: 'google-maps',
        name: 'Google Maps',
        description: 'Location services, directions, and place details',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-google-maps'],
        env: { GOOGLE_MAPS_API_KEY: '' },
        envPlaceholders: { GOOGLE_MAPS_API_KEY: 'your-google-maps-api-key' },
        category: 'cloud',
        features: ['geocode', 'reverse_geocode', 'search_places', 'get_directions', 'distance_matrix'],
        official: true,
    },
    // === Communication ===
    {
        id: 'slack',
        name: 'Slack',
        description: 'Channel management and messaging for Slack workspaces',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-slack'],
        env: { SLACK_BOT_TOKEN: '', SLACK_TEAM_ID: '' },
        envPlaceholders: { SLACK_BOT_TOKEN: 'xoxb-your-bot-token', SLACK_TEAM_ID: 'T0123456789' },
        category: 'communication',
        features: ['list_channels', 'post_message', 'reply_to_thread', 'add_reaction', 'get_channel_history', 'search_messages'],
        official: true,
    },
    // === Utilities ===
    {
        id: 'time',
        name: 'Time',
        description: 'Time and timezone conversion capabilities',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-time'],
        category: 'utilities',
        features: ['get_current_time', 'convert_timezone'],
        official: true,
    },
    {
        id: 'everything',
        name: 'Everything',
        description: 'Reference/test server with prompts, resources, and tools',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-everything'],
        category: 'utilities',
        features: ['echo', 'add', 'longRunningOperation', 'sampleLLM', 'getTinyImage'],
        official: true,
    },
];
//# sourceMappingURL=mcpCatalog.js.map