// Types partagés entre main et renderer
// IPC Channel types
export const IPC_CHANNELS = {
    // Terminal
    TERMINAL_CREATE: 'terminal:create',
    TERMINAL_DATA: 'terminal:data',
    TERMINAL_RESIZE: 'terminal:resize',
    TERMINAL_CLOSE: 'terminal:close',
    TERMINAL_INPUT: 'terminal:input',
    // Workspace
    WORKSPACE_LIST: 'workspace:list',
    WORKSPACE_CREATE: 'workspace:create',
    WORKSPACE_UPDATE: 'workspace:update',
    WORKSPACE_DELETE: 'workspace:delete',
    // Project
    PROJECT_LIST: 'project:list',
    PROJECT_ADD: 'project:add',
    PROJECT_REMOVE: 'project:remove',
    PROJECT_SCAN_CLAUDE: 'project:scanClaude',
    PROJECT_SELECT_DIR: 'project:selectDir',
    // Claude
    CLAUDE_START: 'claude:start',
    CLAUDE_STOP: 'claude:stop',
    CLAUDE_STATUS: 'claude:status',
    CLAUDE_SESSION_END: 'claude:sessionEnd',
    // Kanban
    KANBAN_LIST: 'kanban:list',
    KANBAN_CREATE: 'kanban:create',
    KANBAN_UPDATE: 'kanban:update',
    KANBAN_DELETE: 'kanban:delete',
    KANBAN_WRITE_PROMPT: 'kanban:writePrompt',
    KANBAN_CLEANUP_PROMPT: 'kanban:cleanupPrompt',
    KANBAN_GET_PATH: 'kanban:getPath',
    KANBAN_SELECT_FILES: 'kanban:selectFiles',
    KANBAN_ATTACH_FILE: 'kanban:attachFile',
    KANBAN_ATTACH_FROM_CLIPBOARD: 'kanban:attachFromClipboard',
    KANBAN_REMOVE_ATTACHMENT: 'kanban:removeAttachment',
    KANBAN_GET_WORKING_TICKET: 'kanban:getWorkingTicket',
    KANBAN_WATCH: 'kanban:watch',
    KANBAN_UNWATCH: 'kanban:unwatch',
    KANBAN_FILE_CHANGED: 'kanban:fileChanged',
    // Updates
    UPDATE_CHECK: 'update:check',
    UPDATE_INSTALL: 'update:install',
    UPDATE_UNINSTALL: 'update:uninstall',
    UPDATE_STATUS: 'update:status',
    // Auto-Clauder
    AUTOCLAUDE_APPLY: 'autoclaude:apply',
    AUTOCLAUDE_TEMPLATES: 'autoclaude:templates',
    // Project info
    PROJECT_SCAN_INFO: 'project:scanInfo',
    PROJECT_DEPLOY_CLAUDE: 'project:deployClaude',
    PROJECT_CHECK_CLAUDE: 'project:checkClaude',
    PROJECT_CHECK_PACKAGES: 'project:checkPackages',
    PROJECT_UPDATE_PACKAGE: 'project:updatePackage',
    // File system
    FS_READ_DIR: 'fs:readDir',
    FS_READ_FILE: 'fs:readFile',
    FS_WRITE_FILE: 'fs:writeFile',
    FS_RENAME: 'fs:rename',
    FS_DELETE: 'fs:delete',
    FS_COPY: 'fs:copy',
    FS_MKDIR: 'fs:mkdir',
    FS_EXISTS: 'fs:exists',
    FS_READ_BASE64: 'fs:readBase64',
    FS_OPEN_IN_FINDER: 'fs:openInFinder',
    FS_SEARCH: 'fs:search',
    // Git
    GIT_INIT: 'git:init',
    GIT_STATUS: 'git:status',
    GIT_LOG: 'git:log',
    GIT_BRANCHES: 'git:branches',
    GIT_CHECKOUT: 'git:checkout',
    GIT_PUSH: 'git:push',
    GIT_PULL: 'git:pull',
    GIT_COMMIT: 'git:commit',
    GIT_DIFF: 'git:diff',
    GIT_STASH: 'git:stash',
    GIT_STASH_POP: 'git:stashPop',
    GIT_CREATE_BRANCH: 'git:createBranch',
    GIT_DELETE_BRANCH: 'git:deleteBranch',
    GIT_MERGE: 'git:merge',
    GIT_FETCH: 'git:fetch',
    GIT_STAGE: 'git:stage',
    GIT_UNSTAGE: 'git:unstage',
    GIT_DISCARD: 'git:discard',
    GIT_SHOW: 'git:show',
    GIT_STASH_LIST: 'git:stashList',
    GIT_RENAME_BRANCH: 'git:renameBranch',
    GIT_TAGS: 'git:tags',
    GIT_CREATE_TAG: 'git:createTag',
    GIT_DELETE_TAG: 'git:deleteTag',
    GIT_CHERRY_PICK: 'git:cherryPick',
    GIT_DIFF_BRANCHES: 'git:diffBranches',
    GIT_BLAME: 'git:blame',
    GIT_REMOTES: 'git:remotes',
    GIT_ADD_REMOTE: 'git:addRemote',
    GIT_REMOVE_REMOTE: 'git:removeRemote',
    GIT_RESET_SOFT: 'git:resetSoft',
    // Workspace storage (.workspaces dir)
    WORKSPACE_INIT_DIR: 'workspace:initDir',
    // Session
    SESSION_SAVE: 'session:save',
    SESSION_LOAD: 'session:load',
    SESSION_CLEAR: 'session:clear',
    // Workspace env (virtual env with symlinks)
    WORKSPACE_ENV_SETUP: 'workspace:envSetup',
    WORKSPACE_ENV_PATH: 'workspace:envPath',
    WORKSPACE_ENV_DELETE: 'workspace:envDelete',
    // Project Claude write
    PROJECT_WRITE_CLAUDE_SETTINGS: 'project:writeClaudeSettings',
    PROJECT_WRITE_CLAUDE_MD: 'project:writeClaudeMd',
    // Project scanning (TODO scanner, stats)
    PROJECT_SCAN_TODOS: 'project:scanTodos',
    PROJECT_LOAD_IGNORED_TODOS: 'project:loadIgnoredTodos',
    PROJECT_SAVE_IGNORED_TODOS: 'project:saveIgnoredTodos',
    PROJECT_STATS: 'project:stats',
    // Project notes
    PROJECT_GET_NOTES: 'project:getNotes',
    PROJECT_SAVE_NOTES: 'project:saveNotes',
    // Workspace export/import
    WORKSPACE_EXPORT: 'workspace:export',
    WORKSPACE_IMPORT: 'workspace:import',
    // Prompt templates
    PROMPTS_LIST: 'prompts:list',
    PROMPTS_CREATE: 'prompts:create',
    PROMPTS_UPDATE: 'prompts:update',
    PROMPTS_DELETE: 'prompts:delete',
    // Claude agents & skills
    CLAUDE_LIST_AGENTS: 'claude:listAgents',
    CLAUDE_READ_AGENT: 'claude:readAgent',
    CLAUDE_WRITE_AGENT: 'claude:writeAgent',
    CLAUDE_DELETE_AGENT: 'claude:deleteAgent',
    CLAUDE_LIST_SKILLS: 'claude:listSkills',
    CLAUDE_READ_SKILL: 'claude:readSkill',
    CLAUDE_WRITE_SKILL: 'claude:writeSkill',
    CLAUDE_DELETE_SKILL: 'claude:deleteSkill',
    // Claude defaults library
    CLAUDE_DEFAULTS_PROFILES: 'claude:defaultsProfiles',
    CLAUDE_DEFAULTS_SKILLS: 'claude:defaultsSkills',
    CLAUDE_DEPLOY_PROFILE: 'claude:deployProfile',
    CLAUDE_DEPLOY_SKILL: 'claude:deploySkill',
    CLAUDE_CHECK_DEPLOYED: 'claude:checkDeployed',
    // Claude activity hooks
    CLAUDE_ACTIVITY: 'claude:activity',
    CLAUDE_INSTALL_HOOKS: 'claude:installHooks',
    CLAUDE_CHECK_HOOKS: 'claude:checkHooks',
    CLAUDE_VALIDATE_SETTINGS: 'claude:validateSettings',
    CLAUDE_FIX_SETTINGS: 'claude:fixSettings',
    // MCP
    MCP_GET_HELP: 'mcp:getHelp',
    // API Tester
    API_EXECUTE: 'api:execute',
    API_LOAD: 'api:load',
    API_SAVE: 'api:save',
    API_EXPORT: 'api:export',
    API_IMPORT: 'api:import',
    // Database Explorer
    DB_CONNECT: 'db:connect',
    DB_DISCONNECT: 'db:disconnect',
    DB_TEST_CONNECTION: 'db:testConnection',
    DB_LIST_DATABASES: 'db:listDatabases',
    DB_LIST_SCHEMAS: 'db:listSchemas',
    DB_LIST_TABLES: 'db:listTables',
    DB_TABLE_INFO: 'db:tableInfo',
    DB_EXECUTE_QUERY: 'db:executeQuery',
    DB_CANCEL_QUERY: 'db:cancelQuery',
    DB_LOAD: 'db:load',
    DB_SAVE: 'db:save',
    DB_EXPORT: 'db:export',
    DB_IMPORT: 'db:import',
    DB_BACKUP: 'db:backup',
    DB_BACKUP_LIST: 'db:backupList',
    DB_BACKUP_DELETE: 'db:backupDelete',
    DB_RESTORE: 'db:restore',
    DB_TRANSFER: 'db:transfer',
    DB_QUERY_PROGRESS: 'db:queryProgress',
    DB_BACKUP_LOG: 'db:backupLog',
    // App
    APP_SETTINGS_GET: 'app:settingsGet',
    APP_SETTINGS_SET: 'app:settingsSet',
    APP_NOTIFICATION: 'app:notification',
    APP_VERSION: 'app:version',
    // App Update (electron-updater)
    APP_UPDATE_CHECK: 'appUpdate:check',
    APP_UPDATE_DOWNLOAD: 'appUpdate:download',
    APP_UPDATE_INSTALL: 'appUpdate:install',
    APP_UPDATE_STATUS: 'appUpdate:status',
    // Menu
    MENU_ACTION: 'menu:action',
    // SSH Keys
    SSH_LIST_KEYS: 'ssh:listKeys',
    SSH_GENERATE_KEY: 'ssh:generateKey',
    SSH_READ_PUBLIC_KEY: 'ssh:readPublicKey',
    SSH_IMPORT_KEY: 'ssh:importKey',
    SSH_DELETE_KEY: 'ssh:deleteKey',
    SSH_OPEN_DIRECTORY: 'ssh:openDirectory',
    SSH_SELECT_KEY_FILE: 'ssh:selectKeyFile',
    // Code Analysis
    ANALYSIS_DETECT_TOOLS: 'analysis:detectTools',
    ANALYSIS_RUN: 'analysis:run',
    ANALYSIS_CANCEL: 'analysis:cancel',
    ANALYSIS_PROGRESS: 'analysis:progress',
    ANALYSIS_LOAD_REPORTS: 'analysis:loadReports',
    ANALYSIS_DELETE_REPORT: 'analysis:deleteReport',
    ANALYSIS_CREATE_TICKETS: 'analysis:createTickets',
    ANALYSIS_INSTALL_TOOL: 'analysis:installTool',
    ANALYSIS_INSTALL_PROGRESS: 'analysis:installProgress',
};
//# sourceMappingURL=index.js.map